# Generated by Django 5.2.7 on 2025-11-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_category_id_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_free_preview',
            field=models.BooleanField(default=False, help_text='Mark this lesson as a free preview/demo that all users can access'),
        ),
    ]
